### ISSUE TITLE
doesn't account for DST/standard time changes in the US

### ISSUE THREAD

**Issue by rwygand** [BloodDragon2580/BeledarTimeBroker#1]
The US went to standard time as of Nov 3rd and all the times are now off by 1 hour.

**Comment by BloodDragon2580** [comment]
That means the times must e.g. B. Be made from 5 to 4 o'clock?

**Comment by BloodDragon2580** [comment]
should correct now.

**Comment by rwygand** [comment]
I think the times are now correct, but the math seems to be wrong? It's saying the next spawn is in 12h right now.
![timer](https://github.com/user-attachments/assets/17c37bce-5076-4e02-97b5-9fcc43c3a007)

**Comment by BloodDragon2580** [comment]
I'll test something tomorrow, if it works I'll update it tomorrow.

**Comment by BloodDragon2580** [comment]
I have now uploaded an update, everything should now be fine. The text you have shown in the picture takes a moment to display the correct times.
But I also revised it a bit again.

Please let me know after testing. Whether everything works.

**Comment by rwygand** [comment]
![image](https://github.com/user-attachments/assets/fa3a01fb-d2bb-4b69-ace9-c414c3092554)

Here's another image after updating. The text is a WA that shows the time to spawn, which matches wowhead. This addon seems to be 1h and 3m behind.

Thanks for the fixes, by the way!

**Comment by BloodDragon2580** [comment]
I don't understand. Everything is correct in the EU region. I'll check everything again tomorrow.

**Comment by BloodDragon2580** [comment]
When is your daylies reset? 2am or 3am?

**Comment by rwygand** [comment]
Just got the latest update and that does seem to fix it.  Daily reset in the US, iirc, is 7am PST or 1500 UTC.

**Comment by rwygand** [comment]
I believe there's a function you can call: https://wowpedia.fandom.com/wiki/API_GetQuestResetTime and get rid of the hardcoded US and EU reset times.

**Comment by rwygand** [comment]
Also, FYI ,this is the function from the weakaura I was looking at, which is much simpler. It doesn't populate all spawn times:

`function ()
    local a=(GetQuestResetTime()+3660)%10800  
    return format("\124cffa060ffBeledar's Shadow in\124r \124cffffffff%s%s%ds (%s Local Time)\124r",a>3600 and floor(a/3600).."h "or"",a>60 and floor(a/60%60).."m "or"",a%60,date("%H:%M",a+time()))
end  

`

**Comment by BloodDragon2580** [comment]
Ok, I'll close the entry if it works now. If anything happens again, just let us know. Thanks for the help.
